language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=1.5.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django_nose
  - python setup.py -q install
# command to run tests
script:
  - python manage.py test