language: python
python:
  - "2.7"
# command to install dependencies
branches:
  only:
    - master
env:
  - DJANGO=1.5.1
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO
  - pip install django_nose
  - python setup.py -q install
# command to run tests
script:
  - python manage.py test